### ISSUE TITLE
Devika UI is not responding [ISSUE]

### ISSUE THREAD

**Issue by SyedMuqtasidAli** [stitionai/devika#589]
### Describe your issue
I install devike in my local. install all library, npm.node etc. and I change the API in config.toml I am using groc, openapi, and then I run devika server first and then I run UI of devika UI is display successfully but the model and UI is not responding.

### Screenshots and logs
here is secreenshoot 
![image](https://github.com/stitionai/devika/assets/107794270/4b71f9f3-1051-4a8c-828c-e87406c46438)
![image](https://github.com/stitionai/devika/assets/107794270/bc148a7f-e1c0-427d-882f-bf2eba692b7d)
![image](https://github.com/stitionai/devika/assets/107794270/6fbc8c2b-797f-46e5-bbc8-865e03a8e7d5)
 the last screenshot I click on select model drop down but still nothing Is showing and not accepting input
### Configuration
```
- OS: [e.g. Windows, Linux, MacOS]
- Python version: [e.g. 3.10]
- Node version: [e.g. 18.0.0]
- bun version: [e.g. 0.1.0]
- search engine: [e.g. google]
- Model: [e.g. gpt, cluade, groc]
```

**Comment by veighnsche** [comment]
Same issue

![image](https://github.com/stitionai/devika/assets/16469623/99738e43-30f7-41db-adf3-362a61117201)

Everything is up and running, however the UI is not able to connect to the local DEVIKA backend

**Comment by veighnsche** [comment]
I fixed it in the Devika.py file.

on line 29 or the CORS line

replace that line with this one

`CORS(app, resources={r"/*": {"origins": ["http://localhost:3000", "http://localhost:3001"]}}) # Change the origin to your frontend URL`

**Comment by SyedMuqtasidAli** [comment]
@veighnsche  i write the line but still not working even its still showing 3000 url 
![image](https://github.com/stitionai/devika/assets/107794270/d6323c7c-71ea-45c3-81f6-d8c9cd23c0c2)
![image](https://github.com/stitionai/devika/assets/107794270/e7f386da-beb8-4b91-a73f-029249d1203e)

**Comment by SyedMuqtasidAli** [comment]
@veighnsche  Thanks you very much sir its working now.

**Comment by ARajgor** [comment]
thanks for catching the error. I'll fix it.

**Comment by adamwawrzynski** [comment]
I've got the same problem running a program using docker-compose. I can't select a browser, or model, after clicking on `select project` > `new project` tab I am prompted to pass the project name but after that, nothing changes in the UI and in the logs of docker-compose. In the settings tab, I can switch tabs but there is nothing to be displayed (only in `Appearance` are there options to select).

**Comment by SyedMuqtasidAli** [comment]
@adamwawrzynski https://github.com/stitionai/devika/issues/589#issuecomment-2160583692 try this.

**Comment by Darker117** [comment]
damn. i still have the issue.

**Comment by SyedMuqtasidAli** [comment]
@Darker117 change the url into 3001 in the devika.py it will work fine then.
